# https://knowyourtoolset.com/2018/09/quick-analysis-of-web-logs-iis-or-nginx-with-the-elk-stack
services:
  elk:
    image: sebp/elk
    volumes:
      - ./logs:/logs 
      - ./iis.conf:/etc/logstash/conf.d/iis.conf
    ports: 
      - 5601:5601
      - 9200:9200 
      - 5044:5044
